version: 2

defaults: &defaults
  docker:
    - image: acro5piano/circleci-docker-image-node-10.3.0-awscli-ansible
  working_directory: ~/repo

aliases:
  - &setup_awscli
      name: install aws cli
      command: |
        mkdir ~/.aws
        echo '[default]' >> ~/.aws/credentials
        echo aws_access_key_id = $AWS_ACCESS_KEY_ID >> ~/.aws/credentials
        echo aws_secret_access_key = $AWS_SECRET_ACCESS_KEY >> ~/.aws/credentials
        echo region = ap-northeast-1 >> ~/.aws/credentials

jobs:
  test:
    <<: *defaults
    docker:
      - image: circleci/node:10.3
      - image: mongo:4.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn flow

  deploy:
    <<: *defaults
    steps:
      - checkout
      - run: *setup_awscli
      - run:
          name: install deploy tools
          command: |
            sudo pip3 install awscli
      - run:
          name: deploy
          command: # TODO

workflows:
  version: 2
  master_jobs:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
